services:
  volumeread21:
    build: .
    image: volumeread21-local-dev
    container_name: volumeread21-dev
    ports:
      - "2122:5000"
    volumes:
      - .:/app
      - ./data:/data
      
    environment:
      - FLASK_DEBUG=1
      - DATA_DIR=/data
      # --- ADD THIS LINE ---
      # This tells our Flask app how to find the RSS-Bridge service.
      - RSS_BRIDGE_URL=http://rssbridge
      
    # --- ADD THIS ---
    # This makes sure our app waits for the rssbridge service to start.
    depends_on:
      - rssbridge
  rssbridge:
    image: rssbridge/rss-bridge:latest
    container_name: rssbridge-dev
    ports:
      - "2123:80"
    volumes:
      - ./rss-bridge-config:/config
    restart: unless-stopped